name: Daily Scrape

on:
  schedule:
    - cron: "0 15 * * *"   # daily at 12:00 UTC (~7:00am CT during DST)
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # (Optional) override targets via repo Variables/Secrets
      # - name: Export targets
      #   run: |
      #     echo "APPLE_TEAM_URLS=${{ vars.APPLE_TEAM_URLS }}" >> $GITHUB_ENV
      #     echo "ZILLOW_BOARD_URL=${{ vars.ZILLOW_BOARD_URL }}" >> $GITHUB_ENV

      - name: Run scraper
        run: python scrape.py

      # ⬇️ Commit EVERYTHING produced by the run (JSON + HTML debug, etc.)
      - name: Commit results (JSON + debug files)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update job data + debug artifacts" || echo "No changes"
          git push
