name: Daily Scrape

on:
  schedule:
    - cron: "0 12 * * *"   # 12:00 UTC daily (~6 am CT). Adjust as you like.
  workflow_dispatch:         # allow manual runs

permissions:
  contents: write            # needed to commit JSON updates

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          # You can override these with repo secrets or envs if you like
          APPLE_TEAM_URLS: "https://jobs.apple.com/en-us/search?team=software-quality-automation-and-tools-SFTWR-SQAT,https://jobs.apple.com/en-us/search?team=quality-engineering-OPMFG-QE"
          ZILLOW_BOARD_URL: "https://zillow.wd5.myworkdayjobs.com/en-US/Zillow_Group_External"
        run: python scrape.py

      - name: Commit JSON results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.json || true
          git commit -m "Update job data" || echo "No changes"
          git push
